### ISSUE TITLE
A problem about MMNet

### ISSUE THREAD

**Issue by hello-zhanghao** [mehrdadkhani/MMNet#1]
First of all, thanks for your open source about MMNet. I  am glad to read you article ''Adaptive Neural Signal Detection for Massive MIMO' ' and it is really impressed me, It has a big improvement  in MIMO detection. As described in your article, MMNet does not require any expensive matrix inverse operation, which greatly reduces the complexity of detection. And it  also has great detection performance.
        But when I followd your algorithm, I found a problem. In the article, you proposed two kinds of networks,which called MMNet-iid and MMNet.
        

1. In the i.i.d channel,the MMNet-iid doing very well.
                python offlineTraining.py  --x-size 16 --y-size 64 --snr-min 2 --snr-max 7 --layers 10 -lr 1e-3 --batch-size 500 --train-iterations 10000 --mod QAM_4  --test-batch-size 5000 --linear MMNet_iid --denoiser MMNet --test-every 100

2. but the MMNet does not convergence during training.
python offlineTraining.py  --x-size 16 --y-size 64 --snr-min 2 --snr-max 7 --layers 10 -lr 1e-3 --batch-size 500 --train-iterations 10000 --mod QAM_4  --test-batch-size 5000 --linear MMNet --denoiser MMNet --test-every 100

**Comment by mehrdadkhani** [comment]
Hi,
Please notice that you should use onlineTraining.py on correlated channels.
