### ISSUE TITLE
There is not the module named 'gurobipy' 

### ISSUE THREAD

**Issue by renxiyuan** [mehrdadkhani/MMNet#2]
when we test the classic algorithms the code report a mistake that 'No module named 'gurobipy''.In the genSolver.py 'from gurobipy import *',not the module named 'gurobipy'

**Comment by mehrdadkhani** [comment]
You need to install the gurobi optimizer for the maximum-likelihood ILP solver. You may install gurobi from [here](https://www.gurobi.com).  Gurobi also contains a free version available for academics.

**Comment by renxiyuan** [comment]
&nbsp; Thanks for your reply!
  I recently read some paper and found that​​ ​​t​he​se has​ a little different from yours. For example, in the complexity statistics secti​o​n, your reference 1( and the paper named 'Model-Driven Deep Learning for Joint MIMO Channel Estimation and Signal Detection') indicates that the complexity of OAMP-Net is the third power of the transmitting antenna. At the same time, would you tell me the specific process of Fig.11?
&nbsp;&nbsp; Please take care of yourself during the epidemic.
&nbsp;&nbsp; Looking forward to your reply.

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; your reader
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mehrdadkhani"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 凌晨3:32
收件人:&nbsp;"mehrdadkhani/MMNet"<MMNet@noreply.github.com&gt;;
抄送:&nbsp;"任茜源"<986885146@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [mehrdadkhani/MMNet] There is not the module named 'gurobipy'  (#2)




Closed #2.
